
services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
       - "5433:5432"
    volumes:
       - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: